# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35ticpg236-1L

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Xilinx/IR_TransmistterV2/Microprosessor/Microprosessor.cache/wt [current_project]
set_property parent.project_path D:/Xilinx/IR_TransmistterV2/Microprosessor/Microprosessor.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_mem {
  D:/Xilinx/IR_TransmistterV2/Microprosessor/Complete_Demo_RAM.dat
  D:/Xilinx/IR_TransmistterV2/Microprosessor/Complete_Demo_ROM.dat
}
read_verilog -library xil_defaultlib {
  D:/Xilinx/IR_TransmistterV2/Microprosessor/Microprosessor.srcs/sources_1/new/Frame_Buffer.v
  D:/Xilinx/IR_TransmistterV2/Microprosessor/Microprosessor.srcs/sources_1/new/Generic_counter.v
  D:/Xilinx/IR_TransmistterV2/Microprosessor/Microprosessor.srcs/sources_1/new/VGA_Sig_Gen.v
  D:/Xilinx/IR_TransmistterV2/Microprosessor/Microprosessor.srcs/sources_1/new/ALU.v
  D:/Xilinx/IR_TransmistterV2/Microprosessor/Microprosessor.srcs/sources_1/new/IR_Transmitter.v
  D:/Xilinx/IR_TransmistterV2/Microprosessor/Microprosessor.srcs/sources_1/new/VGA_interface_IO.v
  D:/Xilinx/IR_TransmistterV2/Microprosessor/Microprosessor.srcs/sources_1/new/Processor.v
  D:/Xilinx/IR_TransmistterV2/Microprosessor/Microprosessor.srcs/sources_1/new/IR_Transmitter_IO.v
  D:/Xilinx/IR_TransmistterV2/Microprosessor/Microprosessor.srcs/sources_1/new/Timer.v
  D:/Xilinx/IR_TransmistterV2/Microprosessor/Microprosessor.srcs/sources_1/new/ROM.v
  D:/Xilinx/IR_TransmistterV2/Microprosessor/Microprosessor.srcs/sources_1/new/RAM.v
  D:/Xilinx/IR_TransmistterV2/Microprosessor/Microprosessor.srcs/sources_1/new/LEDs_IO.v
  D:/Xilinx/IR_TransmistterV2/Microprosessor/Microprosessor.srcs/sources_1/new/microprocessor_system.v
}
read_xdc D:/Xilinx/IR_TransmistterV2/Microprosessor/Microprosessor.srcs/constrs_1/new/Microprocessor_constraint.xdc
set_property used_in_implementation false [get_files D:/Xilinx/IR_TransmistterV2/Microprosessor/Microprosessor.srcs/constrs_1/new/Microprocessor_constraint.xdc]

synth_design -top microprocessor_system -part xc7a35ticpg236-1L
write_checkpoint -noxdef microprocessor_system.dcp
catch { report_utilization -file microprocessor_system_utilization_synth.rpt -pb microprocessor_system_utilization_synth.pb }
